### ISSUE TITLE
duckdb@1.1.2 is unavailable in npm repository

### ISSUE THREAD

**Issue by kirankpandi** [duckdb/duckdb-node#135] opened 2024-10-29 14:58 UTC
Unable to install 1.1.2 using `npm`.

```
$  ~ npm install duckdb@1.1.2
npm error code ETARGET
npm error notarget No matching version found for duckdb@1.1.2.
npm error notarget In most cases you or one of your dependencies are requesting
npm error notarget a package version that doesn't exist.
```
Don't see this version listed in the npm duckdb version list also - https://www.npmjs.com/package/duckdb?activeTab=versions

**Comment by archiewood** [comment] 2024-11-05 02:33
duplicate of https://github.com/duckdb/duckdb-node/issues/130?

**Comment by carlopi** [comment] 2024-11-13 14:13
It's out properly on npm / github release. Thanks everyone

**Closed by carlopi** 2024-11-13 14:13 UTC
Labels: reproduced
